name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt || pip install streamlit pandas python-dotenv requests
    - name: Run tests
      run: |
        pytest --maxfail=1 --disable-warnings -v
    - name: Run WAQI fetch script
      env:
        WAQI_API_TOKEN: ${{ secrets.WAQI_API_TOKEN }}
      run: |
        python src/fetch_openaq.py
